Review project
meyer-lab/bi-cytok pull request #74
Opened 2024-05-30 15:55 UTC by armaan-abraham

2024-06-04 21:40 UTC, armaan-abraham commented
@EmilyTLin Would you mind writing a unit test for just the output of the binding model? This will help me swap the current implementation with the imported version confidently. Running the binding model on a few inputs that are representative of the project, and then using the output of the model in an np.allclose would be perfectly fine.

2025-01-10 00:26 UTC, aarmey commented
@samuel-amidon note the instructions here about merging conflicts with main.

2025-01-12 21:49 UTC, aarmey requested changes
A few small adjustments here. Please also adjust down the number of cells to 100 everywhere, so that this successfully builds. We can then explore performance improvements next.

2025-01-12 21:49 UTC, aarmey commented on general_comments.md
> +case letters with `_` to separate words. E.g., `BindingMod.py` ->
If these points have been addressed, this can be removed.

2025-01-12 21:49 UTC, aarmey commented on bicytok/test/test_model.py
>  if __name__ == "__main__":
There's no need for this section. Pytest finds and runs the tests on its own.

2025-01-12 21:49 UTC, aarmey commented on bicytok/test/test_model.py
> +#         cytBindingModel(
Why is this commented out?

2025-01-13 15:55 UTC, aarmey commented
I am removing the dependency on valentbind again because that implementation is more than 10X slower. Should have this pushed shortly.

2025-01-13 19:56 UTC, aarmey commented
@samuel-amidon looks like there is a build failure in Fig. 5.

2025-01-14 01:58 UTC, samuel-amidon commented
Figure 5 still takes 4 hours to build. Is there a limit for how long they can take within the github checks?

2025-01-14 02:45 UTC, aarmey commented
@samuel-amidon doesn't `KL_EMD_2D()` calculate the distances for all targets at once? And isn't it independent of valency? It seems like it could be moved out of the loop, reducing the work a lot.

The build will cancel at 6 hours, but it would be good to take less than 45 mins if at all possible.

2025-01-14 23:17 UTC, samuel-amidon commented
> @samuel-amidon doesn't `KL_EMD_2D()` calculate the distances for all targets at once? And isn't it independent of valency? It seems like it could be moved out of the loop, reducing the work a lot.
> 
> The build will cancel at 6 hours, but it would be good to take less than 45 mins if at all possible.

Done. 

There are a number of things to change in figure 5 that I will change, but I really want to get this branch merged before I start altering the figures too much.

2025-01-14 23:24 UTC, aarmey approved these changes

2025-01-14 23:25 UTC, aarmey commented
@samuel-amidon needed a review approval. Try it now.

2025-01-14 23:25 UTC, merged